### ISSUE TITLE
Bundle install location

### ISSUE THREAD

**Issue by freron** [lchausmann/mailmate-to-orgmode#1]
Hi, I just noticed that your instructions for installing the bundle should be different. It is better to do something like this (and maybe install directly instead of symlinking):

~~~
#!/bin/bash
orgBundlePath=`pwd`
mkdir -p ~/Library/Application\ Support/MailMate/Bundles
cd ~/Library/Application\ Support/MailMate/Bundles/
ln -s ${orgBundlePath}/Org.mmBundle .
~~~

**Comment by lchausmann** [comment]
Thank you. I've updated the readme.
