### ISSUE TITLE
Org 9 changed org-protocol

### ISSUE THREAD

**Issue by mclearc** [lchausmann/mailmate-to-orgmode#2]
Org 9 has [changed](https://orgmode.org/manual/Protocols.html) org-protocol syntax. So `org-protocol://capture://y/` now throws a warning every time it is run. the new syntax should be something like `org-protocol://capture?template=y` but this doesn't seem to be working for some reason.

**Comment by lchausmann** [comment]
I've updated, so that its aligned to the format.

**Comment by mclearc** [comment]
Thanks for the quick response! I wonder if you know why the following doesn't seem to work (I'm definitely neither a ruby nor elisp programmer, but I'm trying to mod your script to open a separate capture window)

```
commandLine="/usr/local/bin/emacsclient -n -c -F "((name . \"Email Capture\") (left . 300) (top . 400) (width . 90) (height . 15))" 'org-protocol:///capture?template=m&url=" + messageURI+ "&title=" + subjectLine + "'"

```

**Comment by mclearc** [comment]
Looks like it was choking on the quote marks. This works.

```
commandLine="/usr/local/bin/emacsclient -n -c -F " +  "'((name . \"Email Capture\") (left . 300) (top . 400) (width . 90) (height . 15))' " +  "'org-protocol:///capture?template=m&url=" + messageURI+ "&title=" + subjectLine + "'"
```

**Comment by lchausmann** [comment]
Excellent. Good job! :)
